version: '3.8'
services:
  db:
    container_name: db
    hostname: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=demoadmin
      - POSTGRES_DB=Flapp
      - POSTGRES_PASSWORD=2019114020
    ports:
      - 5432:5432
  app:
    container_name: app-airlineBooking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - DATABASE_URI=postgresql://demoadmin:2019114020@db/Flapp
    depends_on:
      - db